# The TikTok Effect on Films: Similarity and Topic Diversity in Movie Subtitles Over Time
--- 
### Transpacific Big Data Alliance
#### **Candidate Numbers: 70639 / 73197 / 73329 / 73280**
---

## ABSTRACT
---
The rise of short-form video platforms, most notably TikTok's mainstream adoption in Western markets around 2018, has been widely associated with a structural shift in audience attention patterns. A growing body of research suggests that habitual consumption of short-form content is linked to reduced sustained attention and a preference for faster, more repetitive narrative stimuli (Lin et al., 2024). If this behavioural shift has permeated mainstream cinema, we would expect to observe measurable changes in the narrative structure of popular films over time — specifically, an increase in dialogue redundancy and thematic concentration as filmmakers adapt to audiences less tolerant of sustained narrative complexity.
This study investigates whether such discontinuity is detectable in the textual content of movie scripts. Using sentence embeddings generated by the all-MiniLM-L6-v2 SBERT model and cosine similarity as the primary analytical tool, we construct a Topic Diversity Index (TDI) for 746 films released between 2003 and 2025. Our central hypothesis is that films released after 2018 will exhibit greater narrative repetitiveness (similar sentences) and thematic concentration (fewer topics) than those released before, reflecting the influence of shortened audience attention spans on mainstream screenwriting conventions. We treat 2018 as the pre/post comparison threshold, given TikTok, Instagram, Facebook, and YouTube’s incorporation of short-form video into their platforms and their impact on media consumption, marking a plausible structural break in content pacing expectations.
